base_model_name: "meta-llama/Llama-2-7b-hf"
base_model_path: "/root/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9"
resume_from_checkpoint: "/root/AISMicroOrg/reward_model/results_ft/checkpoint-5000/"
output_dir : "tmp/llama-output"